groups:
- name: ejemplo
  rules:
    - alert: PrometheusJobMissing
      expr: absent(up{job="prometheus"})
      for: 0m
      labels:
        severity: warning
      annotations:
        summary: Prometheus job missing (instance {{ $labels.instance }})
        description: "A Prometheus job has disappeared\n  VALUE = {{ $value }}\n  LABELS = {{ $labels }}"
  
    - alert: HostOutOfMemory
      expr: (node_memory_MemAvailable_bytes / node_memory_MemTotal_bytes < .10)
      for: 0m
      labels:
        severity: warning
      annotations:
        summary: "Posible OOM en {{ $labels.job }}, memoria disponible {{ $value | humanizePercentage }}"
        description: "Node memory is filling up (< 10% left)\n  VALUE = {{ $value }}\n  LABELS = {{ $labels }}"

    - alert: HostDown
      expr: up == 0
      for: 1m 
      labels:
        severity: critical
      annotations:
        summary: "Servicio {{ $labels.job }} caido (host: {{ $labels.instance }})"
        description: "El servicio no responde y Prometheus no puede recolectar métricas.\n  VALUE = {{ $value }}\n  LABELS = {{ $labels }}"

- name: abb_tablero
  rules:
    - alert: CorrienteBajaL1
      expr: abb_current_l1 == 0
      labels:
        severity: critical
      annotations:
        summary: "Corriente en línea L1 bajo a 0 A"
        description: "La corriente en L1 bajo a 0 A ({{ $value }} mA)"

    - alert: CorrienteBajaL2
      expr: abb_current_l2 == 0
      labels:
        severity: critical
      annotations:
        summary: "Corriente en línea L2 bajo a 0 A"
        description: "La corriente en L2 bajo a 0 A ({{ $value }} mA)"

    - alert: CorrienteBajaL3
      expr: abb_current_l3 == 0
      labels:
        severity: critical
      annotations:
        summary: "Corriente en línea L3 bajo a 0 A"
        description: "La corriente en L3 bajo a 0 A ({{ $value }} mA)"

    - alert: CorrienteAltaL1
      expr: abb_current_l1 > 30000
      for: 1m
      labels:
        severity: warning
      annotations:
        summary: "Corriente en línea L1 supera 30 A"
        description: "La corriente en L1 supera 30 A ({{ $value }} mA)"      
    
    - alert: CorrienteAltaL2
      expr: abb_current_l2 > 20000
      for: 1m
      labels:
        severity: warning
      annotations:
        summary: "Corriente en línea L2 supera 20 A"
        description: "La corriente en L2 supera 20 A ({{ $value }} mA)"    

    - alert: CorrienteAltaL3
      expr: abb_current_l3 > 20000
      for: 1m
      labels:
        severity: warning
      annotations:
        summary: "Corriente en línea L3 supera 20 A"
        description: "La corriente en L3 supera 20 A ({{ $value }} mA)"    

    - alert: CorrienteBajaL1
      expr: abb_current_l1 < 10000
      for: 1m
      labels:
        severity: warning
      annotations:
        summary: "Corriente en línea L1 bajo a 10 A"
        description: "La corriente en L1 bajo a {{ $value }} mA"     

    - alert: TensiónBajaL1
      expr: abb_voltage_l1 < 215
      for: 1m
      labels:
        severity: warning
      annotations:
        summary: "Tensión en línea L1 bajo a 215 V"
        description: "La tensión en L1 bajo a {{ $value }} V"          

    - alert: TensiónBajaL2
      expr: abb_voltage_l2 < 215
      for: 1m
      labels:
        severity: warning
      annotations:
        summary: "Tensión en línea L2 bajo a 215 V"
        description: "La tensión en L2 bajo a {{ $value }} V"        

    - alert: TensiónBajaL3
      expr: abb_voltage_l3 < 215
      for: 1m
      labels:
        severity: warning
      annotations:
        summary: "Tensión en línea L3 bajo a 215 V"
        description: "La tensión en L3 bajo a {{ $value }} V"        

- name: docker_container
  rules:
      - alert: docker_swarm_caido
        expr: |
          (time() - max by (servicio_limpio) (
            label_replace(
              container_last_seen{job="cadvisor", name=~"^[^.]+\\.[^.]+\\..*$"},
              "servicio_limpio",
              "$1.$2",
              "name",
              "^([^.]+)\\.([^.]+)\\..*$"
            )
          )) > 60
        for: 1m
        labels:
          severity: critical
        annotations:
          summary: "Fallo en el contenedor Swarm: {{ $labels.servicio_limpio }}"
          description: "La réplica o nodo reflejado en '{{ $labels.servicio_limpio }}' lleva más de 60 segundos sin reportar actividad."

- name: UPS
  rules:
    - alert: UPS en bypass
      expr: ups_status == 4
      for: 1m
      labels:
        severity: warning
      annotations:
        summary: "La UPS paso a estado bypass"
        description: "La UPS se encuentra en estado bypass hace más de 1 minuto."

    - alert: UPS con batería
      expr: ups_status == 5
      for: 1m
      labels:
        severity: warning
      annotations:
        summary: "La UPS paso a estado bateria"
        description: "La UPS se encuentra en estado bateria hace más de 1 minuto."

    - alert: UPS bateria por agotarse
      expr: ups_battery_runtime_remaining_seconds < 3600
      for: 1m
      labels:
        severity: warning
      annotations:
        summary: "La bateria de la UPS esta por agotarse"
        description: "La bateria de la UPS se encuentra por agotarse en {{ $value }} segundos."

- name: webOffline
  rules:
    - alert: webOffline
      expr: probe_success == 0
      for: 5m
      labels:
        severity: critical
      annotations:
        summary: "El sitio web {{ $labels.instance }} está offline"
        description: "El sitio web {{ $labels.instance }} no responde hace más de 5 minutos."