global:
  scrape_interval: 30s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['prometheus:9090']

  - job_name: 'yaku'
    static_configs:
      - targets: ['172.16.48.10:9100']

  - job_name: 'kuntur'
    static_configs:
      - targets: ['172.16.48.7:9100']          

  - job_name: 'wayra'
    static_configs:
      - targets: ['172.16.48.8:9100']      

  - job_name: 'eureka'
    static_configs:
      - targets: ['172.16.48.9:9100']    

  - job_name: 'modbus_exporter'
    static_configs: 
      - targets: ['172.16.48.127:9101']

  - job_name: 'snmp_switch'
    scrape_interval: 1m
    scrape_timeout: 30s
    metrics_path: /snmp
    params:
      module: [if_mib, mikrotik, hrDevice, hrSWInstalled, hrSWRun, hrSWRunPerf, hrStorage, hrSystem]

    static_configs:
      - targets:
          - 172.16.48.1
          - 172.16.48.2
          - 172.16.48.3
          - 172.16.48.4
          - 172.16.48.6

    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target

      - source_labels: [__param_target]
        target_label: instance

      - target_label: __address__
        replacement: snmp_exporter:9116

  - job_name: 'snmp_ups'
    scrape_interval: 1m
    metrics_path: /snmp
    params:
      module: [ups]

    static_configs:
      - targets:
          - 172.16.48.100
          - 172.16.48.101

    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target

      - source_labels: [__param_target]
        target_label: instance

      - target_label: __address__
        replacement: snmp_exporter:9116        

  - job_name: "cadvisor"
    static_configs:
      - targets: 
          - '172.16.48.20:9338'
          - '172.16.48.15:9338'
          - '172.16.48.18:9338'
          - '172.16.48.22:9338'
          - '172.16.48.7:9338'
          - '172.16.48.16:9338'
          - '172.16.48.23:9338'
          - '172.16.48.14:9338'
          - '172.16.48.21:9338'
          - '172.16.48.19:9338'
          - '172.16.48.13:9338'

  - job_name: "node-exporter_swarm"
    static_configs:
      - targets: 
          - '172.16.48.20:9138'
          - '172.16.48.15:9138'
          - '172.16.48.18:9138'
          - '172.16.48.22:9138'
          - '172.16.48.7:9138'
          - '172.16.48.16:9138'
          - '172.16.48.23:9138'
          - '172.16.48.14:9138'
          - '172.16.48.21:9138'
          - '172.16.48.19:9138'
          - '172.16.48.13:9138'

  - job_name: "swarm-prd-m02"
    static_configs:
      - targets: 
          - '172.16.48.13:9138'

  - job_name: 'icmp'
    scrape_interval: 5m
    metrics_path: /probe
    params:
      module: [icmp_check]
    static_configs:
      - targets:
          - 200.16.30.242
          - 172.16.48.127
          - 172.16.48.10
          - 172.16.48.7
          - 172.16.48.8  
          - 172.16.48.9
          - 172.16.48.89
          - 172.16.48.90
          - 172.16.48.91
          - 172.16.48.92
          - 172.16.48.5
          - 172.16.48.71
#          - 172.16.48.50  
#          - 172.16.48.55

    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target

      - source_labels: [__param_target]
        target_label: instance

      - target_label: __address__
        replacement: blackbox-exporter:9115

  - job_name: 'ssh'
    scrape_interval: 5m
    metrics_path: /probe
    params:
      module: [ssh_check]
    static_configs:
      - targets:
          - 172.16.48.10:22
          - 172.16.48.7:22
          - 172.16.48.8:22  
          - 172.16.48.9:22
          - 172.16.48.89:22
          - 172.16.48.90:22
          - 172.16.48.91:22
          - 172.16.48.92:22
          - 172.16.48.5:22
#          - 172.16.48.50:22  
#          - 172.16.48.55:22

    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target

      - source_labels: [__param_target]
        target_label: instance

      - target_label: __address__
        replacement: blackbox-exporter:9115

  - job_name: 'http'
    scrape_interval: 5m
    scrape_timeout: 1m  
    metrics_path: /probe
    params:
      module: [http_check]
    static_configs:
      - targets:
          - https://ohmc.ar/
          - https://webmet.ohmc.ar/ 
          - https://radares.ohmc.ar/
          - https://wrf.ohmc.ar/  
          - https://estaciones.ohmc.ar/
          - https://epec.ohmc.ar/
          - https://estaciones-beta.ohmc.com.ar/
          - https://tehmex.ohmc.ar/
          
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target

      - source_labels: [__param_target]
        target_label: instance

      - target_label: __address__
        replacement: blackbox-exporter:9115

  - job_name: 'snmp_vpn'
    scrape_interval: 1m
    scrape_timeout: 30s
    metrics_path: /snmp
    params:
      module: [eaton_ups]

    static_configs:
      - targets:
          - 192.168.101.6
          - 192.168.101.7
          - 192.168.116.6
          - 192.168.116.7
          - 192.168.117.6
          - 192.168.117.7
          - 192.168.106.6
          - 192.168.106.7
          - 192.168.107.6
          - 192.168.107.7
          
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target

      - source_labels: [__param_target]
        target_label: instance

      - target_label: __address__
        replacement: 172.17.0.1:9117    

alerting:
  alertmanagers:
    - static_configs:
        - targets:
            - alertmanager:9093
rule_files:
  - /etc/prometheus/alert.rules.yml